### ISSUE TITLE
Created 2 Counters with same name, only one displayed.

### ISSUE THREAD

**Issue by nemo83** [fiadliel/prometheus_client_scala#1]
Started to get familiar with the lib and mistakenly created 2 counters with the same name and in the `/metrics` could only see one. 

While it may be normal to see only one of them, I'm wondering whether or not should be possible to register on the same registry 2 metrics with the same name.

**Comment by fiadliel** [comment]
I have yet to decide exactly how to handle this, opinions welcome.

One approach is to throw an exception when attempting to register the counter again, but I dislike throwing exceptions if there's an alternative way.
