### ISSUE TITLE
Play 2.6.0

### ISSUE THREAD

**Issue by avdv** [fiadliel/prometheus_client_scala#22]
Hi.

I just discovered your project... just what I was looking for. :smile: 

Since Play 2.6.0 was released a few days ago, a corresponding `play26_2.11` and `play26_2.12` would be nice!

Cheers.

**Comment by fiadliel** [comment]
Oh no, somebody actually wants to use it 😱 😄 

I created a PR to add this, but needs testing before I release.

**Comment by fiadliel** [comment]
(we use it a lot at work, so don't worry that it's just a toy)

**Comment by avdv** [comment]
Awesome, thanks! :smiley_cat:
